"""make_scan_attempt_id_nullable

Revision ID: 2126be9ffb45
Revises: 510093419eba
Create Date: 2026-02-16 14:52:28.358247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2126be9ffb45'
down_revision = '510093419eba'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table_name in inspector.get_table_names()


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    inspector = sa.inspect(op.get_bind())
    return any(idx.get("name") == index_name for idx in inspector.get_indexes(table_name))


def _drop_index_if_exists(table_name: str, index_name: str) -> None:
    if _index_exists(table_name, index_name):
        op.drop_index(index_name, table_name=table_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Compatibility note:
    # In current baseline (001) table `audit_logs` already exists.
    # Old branches used legacy table `audit_log` and needed a migration path.
    # Keep this migration idempotent across both histories.
    if _table_exists('audit_log') and not _table_exists('audit_logs'):
        op.create_table('audit_logs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('entity_type', sa.String(length=100), nullable=False),
        sa.Column('entity_id', sa.Uuid(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
        op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
        op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
        op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
        op.create_index('ix_audit_logs_entity_type_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
        op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
        op.create_index('ix_audit_logs_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)

        _drop_index_if_exists('audit_log', op.f('ix_audit_log_action'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_action_timestamp'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_entity'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_entity_id'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_entity_type'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_timestamp'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_user_id'))
        _drop_index_if_exists('audit_log', op.f('ix_audit_log_user_timestamp'))
        op.drop_table('audit_log')
    op.drop_constraint(op.f('attempts_sheet_token_hash_key'), 'attempts', type_='unique')
    op.drop_index(op.f('ix_attempts_sheet_token_hash'), table_name='attempts')
    op.create_index(op.f('ix_attempts_sheet_token_hash'), 'attempts', ['sheet_token_hash'], unique=True)
    op.create_index(op.f('ix_attempts_id'), 'attempts', ['id'], unique=False)
    op.create_index('ix_attempts_sheet_token', 'attempts', ['sheet_token_hash'], unique=False)
    op.alter_column('competitions', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_registration_end'), 'competitions', ['registration_end'], unique=False)
    op.create_index(op.f('ix_competitions_registration_start'), 'competitions', ['registration_start'], unique=False)
    op.drop_constraint(op.f('competitions_created_by_fkey'), 'competitions', type_='foreignkey')
    op.create_foreign_key(None, 'competitions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('entry_tokens_registration_id_key'), 'entry_tokens', type_='unique')
    op.drop_constraint(op.f('entry_tokens_token_hash_key'), 'entry_tokens', type_='unique')
    op.drop_index(op.f('ix_entry_tokens_registration_id'), table_name='entry_tokens')
    op.create_index(op.f('ix_entry_tokens_registration_id'), 'entry_tokens', ['registration_id'], unique=True)
    op.drop_index(op.f('ix_entry_tokens_token_hash'), table_name='entry_tokens')
    op.create_index(op.f('ix_entry_tokens_token_hash'), 'entry_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_entry_tokens_id'), 'entry_tokens', ['id'], unique=False)
    op.drop_constraint(op.f('participants_user_id_key'), 'participants', type_='unique')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=True)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.alter_column('scans', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('scans', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.drop_constraint(op.f('scans_uploaded_by_fkey'), 'scans', type_='foreignkey')
    op.create_foreign_key(None, 'scans', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.create_foreign_key(op.f('scans_uploaded_by_fkey'), 'scans', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.alter_column('scans', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('scans', 'attempt_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('participants_user_id_key'), 'participants', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_entry_tokens_id'), table_name='entry_tokens')
    op.drop_index(op.f('ix_entry_tokens_token_hash'), table_name='entry_tokens')
    op.create_index(op.f('ix_entry_tokens_token_hash'), 'entry_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_entry_tokens_registration_id'), table_name='entry_tokens')
    op.create_index(op.f('ix_entry_tokens_registration_id'), 'entry_tokens', ['registration_id'], unique=False)
    op.create_unique_constraint(op.f('entry_tokens_token_hash_key'), 'entry_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('entry_tokens_registration_id_key'), 'entry_tokens', ['registration_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'competitions', type_='foreignkey')
    op.create_foreign_key(op.f('competitions_created_by_fkey'), 'competitions', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_competitions_registration_start'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_registration_end'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.alter_column('competitions', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_attempts_sheet_token', table_name='attempts')
    op.drop_index(op.f('ix_attempts_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_sheet_token_hash'), table_name='attempts')
    op.create_index(op.f('ix_attempts_sheet_token_hash'), 'attempts', ['sheet_token_hash'], unique=False)
    op.create_unique_constraint(op.f('attempts_sheet_token_hash_key'), 'attempts', ['sheet_token_hash'], postgresql_nulls_not_distinct=False)
    if _table_exists('audit_logs') and not _table_exists('audit_log'):
        op.create_table('audit_log',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
        sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_log_user_id_fkey'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
        )
        op.create_index(op.f('ix_audit_log_user_timestamp'), 'audit_log', ['user_id', 'timestamp'], unique=False)
        op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
        op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', [sa.literal_column('timestamp DESC')], unique=False)
        op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
        op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
        op.create_index(op.f('ix_audit_log_entity'), 'audit_log', ['entity_type', 'entity_id'], unique=False)
        op.create_index(op.f('ix_audit_log_action_timestamp'), 'audit_log', ['action', 'timestamp'], unique=False)
        op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)

        _drop_index_if_exists('audit_logs', 'ix_audit_logs_user_timestamp')
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_user_id'))
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_timestamp'))
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_id'))
        _drop_index_if_exists('audit_logs', 'ix_audit_logs_entity_type_id')
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_entity_type'))
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_entity_id'))
        _drop_index_if_exists('audit_logs', 'ix_audit_logs_action_timestamp')
        _drop_index_if_exists('audit_logs', op.f('ix_audit_logs_action'))
        op.drop_table('audit_logs')
    # ### end Alembic commands ###
